git:
  depth: 3
env:
  global:
  - AWS_DEFAULT_REGION: us-west-1
  - S3_PARAMS: '"--acl public-read --cache-control \"public,must-revalidate,proxy-revalidate,max-age=0\""'
  - CMAKE_BUILD_PARALLEL_LEVEL: 4
  - LINUX_CMAKE_PARAMS: '"-DASSIMP_BUILD_ASSIMP_TOOLS=OFF -DASSIMP_BUILD_TESTS=OFF
      -DCMAKE_BUILD_TYPE=Release"'
  - secure: E7WPnunZIVfRFttWQ150UV9TcpR14UbxnJtt78U8wU1rLltZZxcD5zLbUrv+8DV7xtBdDst3N++q9nGFCox2/aoa6hxFt+rWaVSXZida7/3i9/VGmeR83noprobENjYdS1k4v19fKzqJAurJF7cmwyAbMDbsJ1UkTJad3u9TSJQYZHjDOfRsPgL5zcbZlF/giQFQ8SaQo+aFsBFXRoL69ceEJpEYy4mZjX9ZC6iXtCc9dcEk7coDIDPPbW1QzQTTDR+XeDd93XjLjjL/VdnciSkHHuEaejczwWbG3m6jp7gihnwSouk7NtdPcGRaWgZGVnp0Yb0hNag71QNV2G0IA9BOUbHx/IkBtSmNXuWWhWOMP/r50Zv/ab4ORGIbIrTOlgASZEgPH7Q3tvAD1n+WbsAMO8qnt6dYcNZ6xRVceelwmj+L5FMbMWci36jlLlsa07TuzE2wtMujVYhV5CZ3YiqGY3wEC6MiZs3avo0V/V1FNXrOjAnyZFN4C29NXq1mI+gLRrQO1rmLEXWAOzOvubx++DqLOm9gp0Kfe4ONPEQeBF48w50faFr9V+CtdkCisyGdK4bakxwKjr4568RjIxhv1CLknvqIezEDsGjoT5SsewciUCo3vwvHVSw3N7oMc0ELQh++QpCukjbftXCd/fWDJj8MfQBbNs1ZFxMnSFY=
matrix:
  include:
  - name: Linux x64
    dist: xenial
    language: c
    compiler: gcc
    addons:
      apt:
        packages:
        - cmake
        - gcc-4.8
        - g++-4.8
    before_install:
    - pip install --user awscli
    - export PATH=$PATH:$HOME/.local/bin
    script:
    - mkdir build
    - cd build
    - CC=gcc-4.8 CXX=g++-4.8 cmake $LINUX_CMAKE_PARAMS -DCMAKE_C_FLAGS="-U_FORTIFY_SOURCE
      -D_FORTIFY_SOURCE=0" -DCMAKE_SHARED_LINKER_FLAGS=-Wl,--wrap,memcpy ..
    - cmake --build .
    - strip code/libassimp.so
    - git log --first-parent --pretty=format:%H HEAD~2..HEAD~1 > revision.git
    - aws s3 cp code/libassimp.so s3://lwjgl-mips64/nightly/linux/x64/ $S3_PARAMS
    - aws s3 cp revision.git s3://lwjgl-mips64/nightly/linux/x64/libassimp.so.git
      $S3_PARAMS
  - name: Linux arm32
    dist: xenial
    language: c
    compiler: gcc
    addons:
      apt:
        packages:
        - cmake
        - gcc-4.8-arm-linux-gnueabihf
        - g++-4.8-arm-linux-gnueabihf
        - libc6-dev-armhf-cross
    before_install:
    - pip install --user awscli
    - export PATH=$PATH:$HOME/.local/bin
    - sudo sed -i 's/deb http/deb [arch=amd64,i386] http/' /etc/apt/sources.list
    - sudo grep "ubuntu.com/ubuntu" /etc/apt/sources.list | sudo tee /etc/apt/sources.list.d/ports.list
    - sudo sed -i 's/amd64,i386/armhf,arm64/' /etc/apt/sources.list.d/ports.list
    - sudo sed -i 's#http://.*/ubuntu#http://ports.ubuntu.com/ubuntu-ports#' /etc/apt/sources.list.d/ports.list
    - sudo dpkg --add-architecture armhf
    - sudo apt-get update || true
    - sudo apt-get -yq install zlib1g-dev:armhf
    script:
    - mkdir build
    - cd build
    - CC=arm-linux-gnueabihf-gcc-4.8 CXX=arm-linux-gnueabihf-g++-4.8 cmake $LINUX_CMAKE_PARAMS
      -DCMAKE_C_FLAGS="-U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0" ..
    - cmake --build .
    - arm-linux-gnueabihf-strip code/libassimp.so
    - git log --first-parent --pretty=format:%H HEAD~2..HEAD~1 > revision.git
    - aws s3 cp code/libassimp.so s3://lwjgl-mips64/nightly/linux/arm32/ $S3_PARAMS
    - aws s3 cp revision.git s3://lwjgl-mips64/nightly/linux/arm32/libassimp.so.git
      $S3_PARAMS
  - name: Linux arm64
    dist: xenial
    language: c
    compiler: gcc
    addons:
      apt:
        packages:
        - cmake
        - gcc-4.8-aarch64-linux-gnu
        - g++-4.8-aarch64-linux-gnu
        - libc6-dev-arm64-cross
    before_install:
    - pip install --user awscli
    - export PATH=$PATH:$HOME/.local/bin
    - sudo sed -i 's/deb http/deb [arch=amd64,i386] http/' /etc/apt/sources.list
    - sudo grep "ubuntu.com/ubuntu" /etc/apt/sources.list | sudo tee /etc/apt/sources.list.d/ports.list
    - sudo sed -i 's/amd64,i386/armhf,arm64/' /etc/apt/sources.list.d/ports.list
    - sudo sed -i 's#http://.*/ubuntu#http://ports.ubuntu.com/ubuntu-ports#' /etc/apt/sources.list.d/ports.list
    - sudo dpkg --add-architecture arm64
    - sudo apt-get update || true
    - sudo apt-get -yq install zlib1g-dev:arm64
    script:
    - mkdir build
    - cd build
    - CC=aarch64-linux-gnu-gcc-4.8 CXX=aarch64-linux-gnu-g++-4.8 cmake $LINUX_CMAKE_PARAMS
      -DCMAKE_C_FLAGS="-U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0" ..
    - cmake --build .
    - aarch64-linux-gnu-strip code/libassimp.so
    - git log --first-parent --pretty=format:%H HEAD~2..HEAD~1 > revision.git
    - aws s3 cp code/libassimp.so s3://lwjgl-mips64/nightly/linux/arm64/ $S3_PARAMS
    - aws s3 cp revision.git s3://lwjgl-mips64/nightly/linux/arm64/libassimp.so.git
      $S3_PARAMS
  - name: Linux mips64
    dist: xenial
    language: c
    compiler: gcc
    addons:
      apt:
        packages:
        - cmake
        - gcc-5-mips64el-linux-gnuabi64
        - g++-5-mips64el-linux-gnuabi64
        - libc6-dev-mips64el-cross
    before_install:
    - pip install --user awscli
    - export PATH=$PATH:$HOME/.local/bin
    - sudo rm -rf /etc/apt/sources.list
    - sudo sh -c "echo 'deb http://deb.debian.org/debian stretch main' >> /etc/apt/sources.list"
    - sudo dpkg --add-architecture mips64el
    - sudo apt-get update || true
    - sudo apt-get -yq --allow-unauthenticated install zlib1g-dev:mips64el
    script:
    - mkdir build
    - cd build
    - CC=mips64el-linux-gnuabi64-gcc-5 CXX=mips64el-linux-gnuabi64-g++-5 cmake $LINUX_CMAKE_PARAMS
      -DCMAKE_C_FLAGS="-U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0" ..
    - cmake --build .
    - mips64el-linux-gnuabi64-strip code/libassimp.so
    - git log --first-parent --pretty=format:%H HEAD~2..HEAD~1 > revision.git
    - aws s3 cp code/libassimp.so s3://lwjgl-mips64/nightly/linux/mips64/ $S3_PARAMS
    - aws s3 cp revision.git s3://lwjgl-mips64/nightly/linux/mips64/libassimp.so.git
      $S3_PARAMS
  - name: macOS
    language: objective-c
    osx_image: xcode11.3
    compiler: clang
    before_install:
    - brew update
    install:
    - brew install awscli
    script:
    - mkdir build
    - cd build
    - cmake $LINUX_CMAKE_PARAMS -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9 ..
    - cmake --build .
    - strip -u -r code/libassimp.dylib
    - git log --first-parent --pretty=format:%H HEAD~2..HEAD~1 > revision.git
    - aws s3 cp code/libassimp.dylib s3://lwjgl-mips64/nightly/macosx/x64/ $S3_PARAMS
    - aws s3 cp revision.git s3://lwjgl-mips64/nightly/macosx/x64/libassimp.dylib.git
      $S3_PARAMS
